#Adrian Perez Programming III w/ Bill Feild U01

CC = gcc
FILES = main.c deck.c players.c stud_poker.c main.h deck.h players.h stud_poker.h
OUTPUT = poker_game.out

build: $(FILES)
	$(CC) -o $(OUTPUT) $(FILES)
