# Adrian Manuel Perez
# 3180957
# COP 4338 U01 Programming III
# William Feild
# Assigment 6 Shared Processes

CC=gcc -std=c99
FILES=main_shared_process.c shared_process.c
OUTPUT=test_shared_process.out

build: $(FILES)
	$(CC) -lm -o $(OUTPUT) $(FILES)
debug: $(FILES)
	$(CC) -g -lm -o $(OUTPUT) $(FILES)
